package model

// User
const LOGIN_NAME_LOWER_CHAR_LIMIT = 2
const LOGIN_NAME_UPPER_CHAR_LIMIT = 15
const PASSWORD_LOWER_CHAR_LIMIT = 8
const PASSWORD_UPPER_CHAR_LIMIT = 72
const PROFILE_ABOUT_CHAR_LIMIT = 500

// Link
const URL_CHAR_LIMIT = 200

// Summary
const SUMMARY_CHAR_LIMIT = 400

// Links + Summaries
const EARLIEST_STARRERS_LIMIT = 10

// Tag
const CATS_PER_LINK_LIMIT = 15
const CAT_CHAR_LIMIT = 30
