package model

// User
const LOGIN_NAME_LOWER_LIMIT = 2
const LOGIN_NAME_UPPER_LIMIT = 15

const PASSWORD_LOWER_LIMIT = 8
const PASSWORD_UPPER_LIMIT = 72

const PROFILE_ABOUT_CHAR_LIMIT = 500

// Link
const URL_CHAR_LIMIT = 200

// Summary
const SUMMARY_CHAR_LIMIT = 400

// Tag
const NUM_CATS_LIMIT = 10
const CAT_CHAR_LIMIT = 30
