package query

const (
	// Link
	LINKS_PAGE_LIMIT            = 20

	// Contributor
	CONTRIBUTORS_PAGE_LIMIT     = 10

	// Summary
	SUMMARIES_PAGE_LIMIT        = 20

	// Tag
	TAG_RANKINGS_CALC_LIMIT     = 1000
	TAG_RANKINGS_PAGE_LIMIT     = 20
	GLOBAL_CATS_PAGE_LIMIT      = 50
	MORE_GLOBAL_CATS_PAGE_LIMIT = 200
	SPELLFIX_DISTANCE_LIMIT     = 100
	SPELLFIX_MATCHES_LIMIT      = 3
)