name: Modeep backend
run-name: Modeep backend tests
on:
    push:
        branches: [main]

    workflow_dispatch: # Run manually from Actions tab

jobs:
    modeep-backend-tests:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Docker image
              run: |
                  docker build -t modeep-backend-test -f .github/workflows/Dockerfile .

            - name: Run tests in Docker
              env:
                  MODEEP_TEST_DATA_PATH: ${{ secrets.MODEEP_TEST_DATA_PATH }}
                  MODEEP_JWT_SECRET: ${{ secrets.MODEEP_JWT_SECRET }}
              # docker run --rm: remove container after running
              # docker run -v: mount volume
              # docker run -e: set environment variable
              run: |
                  echo "mounting ${{ github.workspace }} to /backend"
                  docker run --rm \
                    -v ${{ github.workspace }}:/backend \
                    -v ${{ env.MODEEP_TEST_DATA_PATH }}:/test_data \
                    -e MODEEP_TEST_DATA_PATH=/test_data \
                    -e MODEEP_ERR_LOG_FILE=/test_data/err.log \
                    -e MODEEP_JWT_SECRET=${{ env.MODEEP_JWT_SECRET }} \
                    modeep-backend-test:latest

            - name: Clean up
              if: always() # run even if previous steps fail
              run: docker rmi modeep-backend-test # docker rmi = docker image rm
